version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - minio
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    networks:
      - app-network

  mongo:
    image: mongo:6
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - ./data/minio:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
